### ISSUE TITLE
Starting the hot tub?

### ISSUE THREAD

**Issue by alonweinstein** [parnic/node-screenlogic#10]
What would be the client command to start the hot tub?

**Comment by parnic** [comment]
https://github.com/parnic/node-screenlogic#setcircuitstatecontrollerid-circuitid-circuitstate
https://github.com/parnic/node-screenlogic#slsetcircuitstatemessage
`controllerId` will probably be 0, `circuitId` can be retrieved (as the documentation explains) by the response to `getControllerConfig()` but will probably be 500 for the spa, and `circuitState` will be 1 for on and 0 for off.
