### ISSUE TITLE
Lights Command questions

### ISSUE THREAD

**Issue by mikemucc** [parnic/node-screenlogic#16]
In the README it lists a bunch of light commands, but says that the command takes an Integer. Is this the correct mapping?

| Number | Meaning |
| ------ | ------- |
| 1 | ScreenLogic.LIGHT_CMD_LIGHTS_OFF
| 2 | ScreenLogic.LIGHT_CMD_LIGHTS_ON
| 3 | ScreenLogic.LIGHT_CMD_COLOR_SET
| 4 | ScreenLogic.LIGHT_CMD_COLOR_SYNC
| 5 | ScreenLogic.LIGHT_CMD_COLOR_SWIM
| 6 | ScreenLogic.LIGHT_CMD_COLOR_MODE_PARTY
| 7 | ScreenLogic.LIGHT_CMD_COLOR_MODE_ROMANCE
| 8 | ScreenLogic.LIGHT_CMD_COLOR_MODE_CARIBBEAN
| 9 | ScreenLogic.LIGHT_CMD_COLOR_MODE_AMERICAN
| 10 | ScreenLogic.LIGHT_CMD_COLOR_MODE_SUNSET
| 11 | ScreenLogic.LIGHT_CMD_COLOR_MODE_ROYAL
| 12 | ScreenLogic.LIGHT_CMD_COLOR_SET_SAVE
| 13 | ScreenLogic.LIGHT_CMD_COLOR_SET_RECALL
| 14 | ScreenLogic.LIGHT_CMD_COLOR_BLUE
| 15 | ScreenLogic.LIGHT_CMD_COLOR_GREEN
| 16 | ScreenLogic.LIGHT_CMD_COLOR_RED
| 17 | ScreenLogic.LIGHT_CMD_COLOR_WHITE
| 18 | ScreenLogic.LIGHT_CMD_COLOR_PURPLE

**Comment by parnic** [comment]
Subtract everything by one.

Yes, the command takes an integer, but each of those constants you listed is an integer, so just pass them to the function.
`sendLightCommand(0, ScreenLogic.LIGHT_CMD_COLOR_MODE_AMERICAN)` for example
