### ISSUE TITLE
RS-485?

### ISSUE THREAD

**Issue by tagyoureit** [parnic/node-screenlogic#2]
Parnic,

Are you able to see what messages the RS-485 bus is sending/receiving?  For example, I'm really interested in the [ControllerConfigMessage](https://github.com/parnic/node-screenlogic/blob/master/messages/SLControllerConfigMessage.js) and how it translates to a request/response on the serial bus.  Let me know if you can see that side of the communications.

It's great you're making progress and I'm trying to understand how (or if) it makes sense to utilize this networking approach in my app.

Tag

**Comment by parnic** [comment]
Sorry, I didn't see this over the weekend.

This library is meant to interact remotely so I don't have any direct access to a bus on the device. That said, I'm working primarily off network sniffing and decompiling their android app, so it may be possible, but I don't have any reference for how to do it.

**Comment by tagyoureit** [comment]
Understood... the one thing (ok, one of the things) I'm looking for is how the Screenlogic knows what equipment is on the Intellitouch board (# of circuits, expansion boards, etc etc).  I haven't been able to find the correct RS485 packets to do that.  If you come across a way to just query those individual components maybe I can use that to see exactly which packets has the same info.

**Comment by parnic** [comment]
Closing since there's no work for me to do here. Happy to chat about it further if I can be of help! :)
