### ISSUE TITLE
How to cancel the default pool delays?

### ISSUE THREAD

**Issue by zredlined** [parnic/node-screenlogic#20]
Love the API! Is there an API I can use to cancel the default pool delays? My controller automatically runs the pool and spa for 2 mins on my system after turning off the spa.

**Comment by parnic** [comment]
I'm not sure! I'd love to add support for that if someone can identify the packet required to do so.

**Comment by bshep** [comment]
i was able to find this in the sources:
    public static final short HLM_POOL_CANCELDELAYSQ = 12580;

however, that command is never used on the android app so i dont know the arguments, my pool doesnt have any 'delays' programmed so i cant try it out either.

**Comment by mikemucc** [comment]
@bshep If you have a cleaner that runs off a booster pump it will have a default delay (that's the only delay I see in my configuration).

**Comment by bshep** [comment]
> @bshep If you have a cleaner that runs off a booster pump it will have a default delay (that's the only delay I see in my configuration).

I pushed the 'cancel delay' button and captured the relevant packet, seems to just have 4 bytes of 00, i can make the changes to the library on my fork and you guys can test, if it works i'll put in a PR to have it merged
