### ISSUE TITLE
Any SmartThings or other smart home integrations?

### ISSUE THREAD

**Issue by coopers98** [parnic/node-screenlogic#22]
Wondering if you know of any projects using your library?  I've been looking into what it would take to integrate ScreenLogic into SmartThings and thought I'd check just in case.

Nice work btw!

**Comment by parnic** [comment]
Check the "Used by" links at the top of the Github page. Someone has written a Homebridge integration. No SmartThings integrations that I'm aware of yet.

**Comment by iannecj** [comment]
It is also the basis for a number of Home Assistant plugins.  Works verywell.

**Comment by coopers98** [comment]
Thanks for the info, I'll take a look!
