### ISSUE TITLE
Schedule Editing

### ISSUE THREAD

**Issue by bshep** [parnic/node-screenlogic#23]
I'm really interested in being able to configure the schedule remotely, i wonder if i can help by providing some packet captures?

I have PC app and wireshark available but i'm not sure what to look for.

**Comment by parnic** [comment]
Captures aren't terribly helpful since I can do that here, and it's hard to find what I'm looking for in a sea of network traffic. More helpful is decompiling the Android app, finding the code that's handling scheduling, and copying it. :) I'd be happy to merge a pull request to add this.

**Comment by bshep** [comment]
Well i'm working on a wireshark dissector for the network traffic, hopefully that helps, i'll look at the android app for ideas as well ;-)

**Comment by bshep** [comment]
I've got most of the scheduling code figured out, unfortunately the android app doesnt let you edit the 'egg timers', i'm trying to see if i can figure it out based on what I already know from the regular schedule.  Will share what I have in a couple of weeks when i have it all working.

**Comment by parnic** [comment]
That's great! Thanks for the update.

**Comment by parnic** [comment]
Closed by #24. Thanks again!
