### ISSUE TITLE
The requested platform "ScreenLogic" was not registered by any plugin v2.0.1

### ISSUE THREAD

**Issue by maxmuller** [parnic/node-screenlogic#34]
Hi, I just stumbled across this great plugin and tried to get it setup in HOOBS. I have several other plugins working with HOOBS, however the ScreenLogic plugin fails with this message:

6/24/2020, 9:23:02 AM Loaded plugin "homebridge-screenlogic".
6/24/2020, 9:23:02 AM The requested platform "ScreenLogic" was not registered by any plugin.
6/24/2020, 9:23:02 AM Your config.json is requesting the platform "ScreenLogic" which has not been published by any installed plugins.

My config:
        {
            "platform": "ScreenLogic",
            "plugin_map": {
                "plugin_name": "homebridge-screenlogic"
            },
            "hidePoolTemperatureSensor": false,
            "hideSpaTemperatureSensor": false,
            "hideAirTemperatureSensor": false,
            "hidePoolThermostat": false,
            "hideSpaThermostat": false,
            "statusPollingSeconds": 60
        }

HOOBS 3.2.6 (up to date)
Node 12.16.2

Any ideas?

**Comment by parnic** [comment]
I'm afraid I have no idea what HOOBS is and the homebridge plugin is not mine. You'd need to enter an issue over there :). https://github.com/schemers/homebridge-screenlogic
