### ISSUE TITLE
Get Circuit State (on, off, etc.)

### ISSUE THREAD

**Issue by Spencer1O1** [parnic/node-screenlogic#38]
We are trying to get the circuit state of something like the waterfalls so we know if they are on or off. We read all the documentation and couldn't figure out how to do this. Did we miss something or is this impossible?

We tried getCircuitByDeviceId(), but it said the function is not defined.
We also tried looking at ```...}).on('controllerConfig', function (config) {
config.bodyArray[<index of circuit>]...```, but it didn't give us the information we need.

**Comment by parnic** [comment]
This is the PoolStatus message. Inspect `circuitArray` for the circuit `id` you want, then look at its `state` to see if it's on or off.

https://github.com/parnic/node-screenlogic#properties-2
