### ISSUE TITLE
Get current light color for pool/spa lights

### ISSUE THREAD

**Issue by WhiteFire356** [parnic/node-screenlogic#39]
I checked the SLControllerConfigMessage in bodyArray and colorArray, and I checked the SLPoolStatusMessage in circuit array. Am I missing something?

Also as a side question, is it possible to target specific group of lights, for example pool lights, or spa lights when doing sendLightCommand?

**Comment by parnic** [comment]
> I checked the SLControllerConfigMessage in bodyArray and colorArray, and I checked the SLPoolStatusMessage in circuit array. Am I missing something?

The library doesn't support retrieving current color of a light. I don't know where/if that's available in the official app either, which is how I've been able to add features to this library at all. Best you could do is remember internally what the last color command you issued was and assume it's still that.

> Also as a side question, is it possible to target specific group of lights, for example pool lights, or spa lights when doing sendLightCommand?

I wish. If that's possible, I haven't found the means by which to do it. I left [a comment in the readme](https://github.com/parnic/node-screenlogic#sendlightcommandcontrollerid-command) alluding to this.

I'd be excited to accept PRs to add these features if they're available.

**Comment by WhiteFire356** [comment]
> I'd be excited to accept PRs to add these features if they're available.

I would be willing to check out the official app's code and help out if you could provide me with an apk or whatever you use to check.

**Comment by parnic** [comment]
> > I'd be excited to accept PRs to add these features if they're available.
> 
> I would be willing to check out the official app's code and help out if you could provide me with an apk or whatever you use to check.

Check [this comment](https://github.com/parnic/node-screenlogic/issues/17#issuecomment-583880747) out.

**Comment by bshep** [comment]
I agree with parnic, I don't think either of those functions are possible.

**Comment by WhiteFire356** [comment]
> I agree with parnic, I don't think either of those functions are possible.

I have been looking through the code and have come to the same conclusion.

The only way I can see possible is if we could somehow modify the hardware to accept special requests. I will look into this.

**Comment by bshep** [comment]
> > I agree with parnic, I don't think either of those functions are possible.
> 
> I have been looking through the code and have come to the same conclusion.
> 
> The only way I can see possible is if we could somehow modify the hardware to accept special requests. I will look into this.

That would be great, I was able to take apart the firmware upgrade utility for the screenlogic adapter and found the firmware file, unfortunately it uses a relatively obscure chip (a rabbit microprocessor) and uses DynamicC as the toolchain.  I was unable to disassemble the firmware as the tools i could find did not have support for that chip.  Granted I'm not too skilled in this kind of thing so maybe someone with more experience could take a look.

**Comment by parnic** [comment]
Going to close this out for now as it seems we all agree it's impossible, at least with the information currently available. If you make other discoveries, feel free to open new issues!
