### ISSUE TITLE
any tips on how to change light colors...

### ISSUE THREAD

**Issue by bmf7777** [parnic/node-screenlogic#4]
i have this working for my pentair controller ... i'd like to add functionality to change the light colors

**Comment by pgregg88** [comment]
Are you looking to select from the pre-configured list of colors or set custom colors? I’m looking to do the later. It should be possible based on the save/recall capability. I’m thinking we need the ability to insert our own custom rgb values wherever the “save” function stores these and then run the “recall” option. Does this sound viable?

**Comment by parnic** [comment]
Yes, whenever I find the time for this, my goal is to be able to set custom colors.

**Comment by parnic** [comment]
This implementation is barebones and only does what I was able to find easily in the official app's source code. I'd love to do more with this, so any pull requests adding functionality would be welcomed.
