### ISSUE TITLE
SenderID's don't work with an old version of the library ... duh.

### ISSUE THREAD

**Issue by mikemucc** [parnic/node-screenlogic#46]
...nevermind, had old code...

**Comment by mikemucc** [comment]
Screenlogic version:     
`"node-screenlogic": "^1.6.0-1"`

**Comment by mikemucc** [comment]
Nevermind, figured out the problem... the senderID code isn't released to NPM.

Can we get a new tag?

**Comment by parnic** [comment]
Yeah I can tag when I get some time. :)

**Comment by parnic** [comment]
Tagged.
