### ISSUE TITLE
CoolSetpoint on Spa tracks outdoor air temp?

### ISSUE THREAD

**Issue by michaelmaston** [parnic/node-screenlogic#57]
I noticed today that the cool setpoint for a spa body (the data that comes back in SLPoolStatusMessage.js) seems to track along with the air temperature reading.  At first I thought I had a bug somewhere parsing the data or updating my UI but when I look at the actual data coming back from the controller it matches what I see.

It probably makes sense in some way as a cool setpoint for a spa doesn't seem very useful but I thought I'd ask as I didn't see any reference to it in the code or docs that the controller would send back the air temp in the cool setpoint value for a spa.  The pool setpoints (heat and cool) seem reasonable and I don't see them change as the air temp does.

**Comment by parnic** [comment]
Interesting. I will update the documentation to reflect this finding. The official app does track this property as the spa's "cool setpoint", but never actually uses that value anywhere that I can tell, so I'm assuming it was just easier to process the 2 bodies in a loop, then effectively ignore the spa's "cool" setpoint. Thanks for passing this info along!

**Comment by michaelmaston** [comment]
Completely makes sense that it wasn't handled differently as I suspect it doesn't do much useful (or I don't understand what to use it for).  It was probably easier for Pentair to keep the fields consistent between the two rather than special case excluding it for spas.    I was sure I was just updating it incorrectly somewhere until I went thru a few packets to make sure it really was reporting it that way. 

Take care!
