### ISSUE TITLE
feature request: Access "history" data

### ISSUE THREAD

**Issue by yeloshak** [parnic/node-screenlogic#59]
I would really like to access the data that shows up in "history" on the pentair screen logic app. Pool temp, spa temp, outdoor temp and heater running time. It also shows pool mode and spa mode. 

maybe its easier if I monitor those myself continuously, but curious if it is easy to pull from the device. Also not sure how much data it stores. 

thanks.

**Comment by parnic** [comment]
Please let me know if https://github.com/parnic/node-screenlogic/commit/485b494ea84a997841737cdaf0141280453cbaf2 covers what you need. As far as I can tell, this is all the historical data available from the system. It's also the first event (in recent memory, at least) that required a separate callback for the data actually being ready to go, so implementation required a bit more forensics than usual. I think I got it, though!
