### ISSUE TITLE
Set pump speeds

### ISSUE THREAD

**Issue by tagyoureit** [parnic/node-screenlogic#62]
Creating a new issue so we don't pollute the other thread.

When I get back the pump status the data is this:
```
Pump 0: 
{"pumpCircuits":
[
{"circuitId":1,"speed":5,"isRPMs":true},
{"circuitId":6,"speed":2000,"isRPMs":true},
{"circuitId":7,"speed":2500,"isRPMs":true},
{"circuitId":8,"speed":3250,"isRPMs":true},
{"circuitId":18,"speed":1320,"isRPMs":true},
{"circuitId":0,"speed":1000,"isRPMs":true},
{"circuitId":0,"speed":1000,"isRPMs":true},
{"circuitId":0,"speed":1000,"isRPMs":true}
],
"pumpType":2,
"isRunning":true,
"pumpWatts":506,
"pumpRPMs":2000,
"pumpUnknown1":0,
"pumpGPMs":255,
"pumpUnknown2":255}
```

I tried both (in your original code):
* `this.setPumpFlow(0,5,1010,true);`  (for the 5th index in the array)
* `this.setPumpFlow(0,18,1010,true);`  (for the circuit id of 18)

Neither worked.  What am I missing here?

And a follow on item- looks like in order to change the pump, or circuit itself, I'll need to call 12568 and update the entire pool config.  Does that sound correct?

**Comment by parnic** [comment]
I'll try to take a look at it soon. Here's what that message came in, if it helps: https://github.com/parnic/node-screenlogic/pull/28

**Comment by apizzi69** [comment]
Any updates on this @parnic ?

**Comment by parnic** [comment]
@apizzi69 sorry, I forgot this issue existed. I gave an update over here:

https://github.com/parnic/node-screenlogic/issues/61#issuecomment-1348693063

This command works for me. If others can give me info about their system (wireshark dumps or whatever is easiest) would help me figure it out for other systems, pump types, whatever the issue is.

**Comment by apizzi69** [comment]
@parnic Thanks! 

Any chance i can get an email to communicate better and work with you on this? I would like to help out with this initiative!

**Comment by parnic** [comment]
> @parnic Thanks!
> 
> Any chance i can get an email to communicate better and work with you on this? I would like to help out with this initiative!

Sure, it's on my Github profile.

**Comment by apizzi69** [comment]
ok got it! @parnic !

**Comment by tagyoureit** [comment]
I did get this working in my `typescript` branch.  Made comments in the other thread.  Thx!
