### ISSUE TITLE
Is UDP Broadcast the same as mdns/dns service discovery?

### ISSUE THREAD

**Issue by ColtonIdle** [parnic/node-screenlogic#74]
Hello still kinda new to node and networking. I'm working on something where I can search do dns service discovery and I can find local devices on my network by searching for `_http._tcp`. But im not sure how to search via dns service discovery for screenlogic. any pointers?

**Comment by parnic** [comment]
Broadcasts send a blind message that can be received by any device listening for them, which can then reply with its details. SSDP is a common way of finding servers via broadcasts. I don't know much about mdns, but based on a quick wikipedia scan, it looks like it's more about resolving a name to an IP address, which is very different from what a broadcast is trying to do.

**Comment by ColtonIdle** [comment]
Ohhh! TIL. I didn't know SSDP was a thing. I thought the "standard" thing was just using mdns. Appreciate it. I will try to look up how to do ssdp.
